name: materials-example
channels:
  - conda-forge
dependencies:
  - ipympl
  - ipywidgets
  - jupyterlab=2
  - matplotlib
  - nbresuse
  - numpy
  - pandas
  - python=3
  - biopython
  - psutil
  - ipycytoscape=0.2.2
  - networkx
  - reportlab
